name: Run Bitping Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bitping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Bitping Docker image
        run: |
          docker build -t bitpingd-login .

      - name: Run Bitping container and keep it alive
        run: |
          docker run \
            --mount type=volume,source=bitpingd-volume,target=/root/.bitpingd \
            bitpingd-login