name: Run Bitping Container

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t bitpingd-login .

      - name: Run container
        run: |
          docker run --rm \
            --mount type=volume,source=bitpingd-volume,target=/root/.bitpingd \
            bitpingd-login